export const CHANNELS: string[] = [
  // UK Terrestrial & Freeview
  "BBC One HD",
  "BBC Two HD",
  "BBC Three HD",
  "BBC Four HD",
  "ITV HD",
  "ITV2",
  "ITV3",
  "ITV4",
  "ITVBe",
  "Channel 4 HD",
  "Channel 5 HD",
  "E4",
  "E4 Extra",
  "More4",
  "Film4",
  "5Star",
  "5USA",
  "5Action",
  "Dave",
  "W",
  "Really",
  "Drama",
  "Yesterday",
  "Gold",
  "CBBC",
  "CBeebies",

  // Sky Entertainment
  "Sky One HD",
  "Sky Two HD",
  "Sky Atlantic HD",
  "Sky Witness HD",
  "Sky Comedy HD",
  "Sky Crime HD",
  "Sky Documentaries HD",
  "Sky History HD",
  "Sky History 2 HD",
  "Sky Nature HD",
  "Sky Arts HD",
  "Sky Max HD",
  "Sky Showcase HD",
  "Sky Cinema Action HD",
  "Sky Cinema Comedy HD",
  "Sky Cinema Drama HD",
  "Sky Cinema Family HD",
  "Sky Cinema Premiere HD",
  "Sky Cinema Sci-Fi & Horror HD",
  "Sky Cinema Thriller HD",
  "Sky Cinema Select HD",

  // Sky Sports
  "Sky Sports Main Event HD",
  "Sky Sports Premier League HD",
  "Sky Sports Football HD",
  "Sky Sports Cricket HD",
  "Sky Sports Golf HD",
  "Sky Sports F1 HD",
  "Sky Sports Arena HD",
  "Sky Sports Mix HD",
  "Sky Sports News HD",
  "Sky Sports Tennis HD",
  "Sky Sports Racing HD",

  // BT Sport / TNT Sports
  "TNT Sports 1 HD",
  "TNT Sports 2 HD",
  "TNT Sports 3 HD",
  "TNT Sports 4 HD",
  "BT Sport ESPN HD",

  // News
  "Sky News HD",
  "BBC News HD",
  "GB News HD",
  "Talk TV",
  "CNN International",
  "Fox News",
  "Al Jazeera English",
  "Bloomberg",
  "CNBC",
  "Euronews",
  "France 24 English",
  "RT News",

  // Entertainment
  "Challenge",
  "Alibi",
  "Crime+Investigation",
  "True Crime",
  "CBS Reality",
  "Comedy Central",
  "Comedy Central Extra",
  "Paramount Network",
  "Horror Channel",
  "TCM",
  "Sony Movies",
  "Sony Movies Action",
  "Sony Movies Classic",
  "AMC",
  "Lifetime",
  "Pick",
  "TLC",
  "HGTV",
  "Food Network",
  "Travel Channel",
  "Home",
  "Smithsonian Channel",
  "Fashion TV",
  "Bravo",
  "FX",

  // Kids
  "Nickelodeon",
  "Nick Jr",
  "Nicktoons",
  "Disney Channel",
  "Disney Junior",
  "Disney XD",
  "Cartoon Network",
  "Boomerang",
  "Pop",
  "Tiny Pop",
  "Baby TV",

  // Music
  "MTV",
  "MTV Base",
  "MTV Hits",
  "MTV Music",
  "VH1",
  "Kiss TV",
  "Magic TV",
  "Heat TV",
  "Kerrang!",
  "The Box",
  "4Music",
  "Clubland TV",
  "Chart Show TV",
  "Box Hits",
  "Absolute Radio TV",

  // Discovery / Factual
  "Discovery Channel",
  "Discovery Science",
  "Discovery History",
  "Discovery Turbo",
  "National Geographic HD",
  "Nat Geo Wild HD",
  "Animal Planet",
  "History Channel",
  "DMAX",
  "Quest",
  "Quest Red",

  // US Networks
  "NBC",
  "ABC",
  "CBS",
  "FOX",
  "PBS",
  "ESPN",
  "ESPN2",
  "FS1",
  "FS2",
  "CBS Sports Network",
  "NFL Network",
  "NBA TV",
  "NHL Network",
  "MLB Network",
  "Tennis Channel",
  "Golf Channel",
  "USA Network",
  "Oxygen",
  "Starz",
  "Showtime",
  "HBO",
  "AMC+",
  "Univision",
  "Telemundo",

  // Irish Channels
  "RTE One HD",
  "RTE Two HD",
  "RTE One +1",
  "Virgin Media One",
  "Virgin Media Two",
  "Virgin Media Three",
  "Virgin Media Four",
  "TG4",
  "Oireachtas TV",
  "RTE News Now",
  "RTE Jr",
  "GAA TV",
  "LOI TV",

  // Sports (Extra)
  "beIN Sports 1 HD",
  "beIN Sports 2 HD",
  "beIN Sports 3 HD",
  "Eurosport 1 HD",
  "Eurosport 2 HD",
  "eir Sport 1",
  "eir Sport 2",
  "Racing TV",
  "Setanta Sports 1",
  "Setanta Sports 2",
  "Setanta Sports 3",
  "Setanta Sports 4",
  "Premier League TV",
  "DAZN 1",
  "DAZN 2",
  "DAZN 3",
  "DAZN 4",
  "Sky Sports Premier League",
  "Sky Sports Football",

  // Streaming / VOD
  "Netflix",
  "Disney+",
  "Amazon Prime Video",
  "HBO Max",
  "Apple TV+",
  "Peacock",
  "Paramount+",
  "DAZN",
  "Now TV",
  "Britbox",
  "ITVX",
  "BBC iPlayer",
  "All 4",
  "My5",
];
